src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    public function __construct()
    {
        $this->published_at = new \DateTimeImmutable();
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: false)]
    private ?\DateTimeImmutable $published_at = null;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank(message: "Le titre est requis")]
    #[Assert\Length(min: 3, minMessage: "Le titre doit etre au minimum {{limit}} caractères", max: 10, maxMessage: "Le titre ne doit pas dépasser {{limit}} caractères")]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le contenu est requis")]
    #[Assert\Length(min: 3, minMessage: "Le contenu doit etre au minimum {{limit}} caractères", max: 255, maxMessage: "Le contenu ne doit pas dépasser {{limit}} caractères")]
    private ?string $content = null;

    #[ORM\ManyToOne(inversedBy: 'articles')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\Choice(
        choices: [1, 2],
        message: 'Vous devez selectionner au moins une catégorie',
    )]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeImmutable $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Article::class)]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setCategory($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getCategory() === $this) {
                $article->setCategory(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->name;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
                'attr' => [
                    'class' => ''
                ]
            ])
            ->add('content')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArticleRepository $articleRepository): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->save($article, true);

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->save($article, true);

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $articleRepository->remove($article, true);
        }

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        $articles = $articleRepository->findAll();
        return $this->render('article/index.html.twig', [
            'articles' => $articles
        ]);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
<div class="w-96 mx-auto shadow-md rounded bg-gray-50 p-4">

	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button class="px-4 py-2 bg-blue-500 shadow text-white font-medium hover:bg-blue-700 transition duration-500">
		{{ button_label|default('Save') }}
	</button>
	{{ form_end(form) }}

</div>

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index
{% endblock %}

{% block body %}
	<div class="container max-w-7xl mx-auto flex justify-between items-center mb-4">
		<h1 class="text-2xl text-red-400 uppercase">Gérer les actualités</h1>
		<a class="" href="{{ path('app_article_new') }}">
			<svg xmlns="http://www.w3.org/2000/svg" width="3rem" height="3rem" viewbox="0 0 24 24"><path fill="#16a34a" d="M11 17h2v-4h4v-2h-4V7h-2v4H7v2h4v4Zm1 5q-2.075 0-3.9-.788t-3.175-2.137q-1.35-1.35-2.137-3.175T2 12q0-2.075.788-3.9t2.137-3.175q1.35-1.35 3.175-2.137T12 2q2.075 0 3.9.788t3.175 2.137q1.35 1.35 2.138 3.175T22 12q0 2.075-.788 3.9t-2.137 3.175q-1.35 1.35-3.175 2.138T12 22Z"/></svg>
		</a>
	</div>
	<div class="container  max-w-7xl w-100 mx-auto">
		<div class="flex flex-col">
			<div class="w-full">
				<div class="border-b border-gray-200 shadow">
					<table class="divide-y divide-gray-300 w-100">
						<thead class="bg-gray-50">
							<tr>
								<th class="px-6 py-2 text-xs text-gray-500">
									#
								</th>
								<th class="px-6 py-2 text-xs text-gray-500">
									Title
								</th>
								<th class="px-6 py-2 text-xs text-gray-500">
									Content
								</th>
								<th class="px-6 py-2 text-xs text-gray-500">
									Published_At
								</th>
								<th class="px-6 py-2 text-xs text-gray-500">
									Gategory
								</th>
								<th class="px-6 py-2 text-xs text-gray-500">
									Edit
								</th>
								<th class="px-6 py-2 text-xs text-gray-500">
									Delete
								</th>
							</tr>
						</thead>
						<tbody class="bg-white divide-y divide-gray-300">
							{% for article in articles %}
								<tr class="whitespace-nowrap">
									<td class="px-6 py-4 text-sm text-gray-500">
										{{ article.id }}
									</td>
									<td class="px-6 py-4">
										<div class="text-sm text-gray-900">
											{{ article.title }}
										</div>
									</td>
									<td class="px-6 py-4">
										<div class="text-sm text-gray-500 ">
											{% if article.content|length > 90 %}
												{{ article.content|slice(0, 90) ~ '...' }}
											{% else %}
												{{ article.content }}
											{% endif %}
										</div>
									</td>
									<td class="px-6 py-4 text-sm text-gray-500">
										{{ article.publishedAt ? article.publishedAt|date('Y-m-d H:i:s') : '' }}
									</td>
									<td class="px-6 py-4 text-sm text-gray-500">
										{{ article.category ? article.category.name : 'none' }}
									</td>
									<td class="px-6 py-4">
										<a href="{{ path('app_article_edit', {'id': article.id}) }}">
											<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-blue-400" fill="none" viewbox="0 0 24 24" stroke="currentColor">
												<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
											</svg>
										</a>
									</td>
									<td class="px-6 py-4">
										<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Êtes-vous sur de vouloir supprimer cet article ?');" class="d-inline-block">
											<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
											<button class="btn btn-danger">
												<a href="#">
													<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-red-400" fill="none" viewbox="0 0 24 24" stroke="currentColor">
														<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
													</svg>
												</a>
											</button>
										</form>

									</td>
								</tr>
							{% else %}
								<tr>
									<td colspan="5">no records found</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>


	{# <h1>Article index</h1>
		
		    <table class="table">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Published_at</th>
		                <th>Title</th>
		                <th>Content</th>
		                <th>actions</th>
		            </tr>
		        </thead>
		        <tbody>
		        {% for article in articles %}
		            <tr>
		                <td>{{ article.id }}</td>
		                <td>{{ article.publishedAt ? article.publishedAt|date('Y-m-d H:i:s') : '' }}</td>
		                <td>{{ article.title }}</td>
		                <td>{{ article.content }}</td>
		                <td>
		                    <a href="{{ path('app_article_show', {'id': article.id}) }}">show</a>
		                    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>
		                </td>
		            </tr>
		        {% else %}
		            <tr>
		                <td colspan="5">no records found</td>
		            </tr>
		        {% endfor %}
		        </tbody>
		    </table>
		
		    <a href="{{ path('app_article_new') }}">Create new</a> #}
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1 class="text-center text-2xl text-red-400 mt-6 mb-4">Ajouter un article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Published_at</th>
                <td>{{ article.publishedAt ? article.publishedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ article.content }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_article_index') }}">back to list</a>

    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<style>
			.error {
				color: #b91c1c;
			}
		</style>
	</head>

	<body>
		<div class="text-center w-100 py-4 bg-gray-100 text-2xl mb-4">Actualités</div>
		{% block body %}{% endblock %}


	</body>

</html>

templates/form/tailwind.html.twig
{% use 'tailwind_2_layout.html.twig' %}


{%- block form_row -%}
{%- set row_attr = row_attr|merge({ class: row_attr.class|default(row_class|default('mb-4')) }) -%}
{{- parent() -}}{%- endblock form_row -%}
    {%- block widget_attributes -%}{%- set attr = attr|merge({ class: attr.class|default(widget_class|default('
    mt-1 rounded w-full
    transition-property: all;
    transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
    transition-duration: 800ms;
    ')) ~ (disabled ? ' ' ~ widget_disabled_class|default('border-gray-300 text-gray-500')) ~ (errors|length ? ' ' ~ widget_errors_class|default('border-red-700')) }) -%}{{- parent() -}}{%- endblock widget_attributes -%}{%- block form_errors -%}{%- if errors|length > 0 -%}<ul>
{%- for error in errors -%}
	<li class="{{ error_item_class|default('error') }}">{{ error.message }}</li>
{%- endfor -%}</ul>{%- endif -%}{%- endblock form_errors -%}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/Workspace/Symfony/projet_crud/src/Controller/HomeController.php'|file_link(0) }}">src/Controller/HomeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/Workspace/Symfony/projet_crud/templates/home/index.html.twig'|file_link(0) }}">templates/home/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}